---
- name: Create EC2 instance
  hosts: all
  connection: local
  gather_facts: False
  tasks:
    - name: Create a Test Server
      ec2:
        image: ami-0c20b8b385217763f
        instance_type: t2.micro
        group: AnsibleSecurityGroup
        key_name: ansibleSSH
        region: ap-southeast-1
        instance_tags:
          Name: CreatedByAnsible